language: node_js
node_js:
  - '10'
cache: yarn
script:
  - yarn lint
  - yarn test --coverage
  - yarn tsc
  - yarn storybook:build
after_success:
  - yarn coveralls
deploy:
  provider: pages
  local_dir: example
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  slack: in2:t4HfbJOtRL7uekgIPh2DUIKb
  email: false
